language: python
python:
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - 3.1
  - 3.2
  - 3.3
  - 3.4
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
script:
  - py.test
after_success:
  - pip install python-coveralls
  - coveralls
